version: '3.7'

volumes:
  pg_vol_auth:
  pg_vol_chat-server:

services:
  pg-auth:
    image: postgres:16-alpine
    env_file:
      - ./.env
    ports:
      - "54321:5432"
    volumes:
      - pg_vol_auth:/var/lib/postgresql/data

  pg-chat-server:
    image: postgres:16-alpine
    env_file:
      - ./.env
    ports:
      - "54322:5432"
    volumes:
      - pg_vol_chat-server:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    depends_on:
      - pg-auth
      - pg-chat-server

  auth:
    container_name: auth
    image: auth
    command: -config-path=.env
    depends_on:
      - pg-auth

  chat-server:
    container_name: chat-server
    image: chat-server
    command: -config-path=.env
    depends_on:
      - pg-chat-server