version: '3.7'

volumes:
  pg_vol_auth:
  pg_vol_chat-server:

services:
  pg-auth-prod:
    image: postgres:16-alpine
    env_file:
      - ./.env.prod
    ports:
      - "${PG_PORT_AUTH}:5432"
    volumes:
      - pg_vol_auth:/var/lib/postgresql/data

  pg-chat-server-prod:
    image: postgres:16-alpine
    env_file:
      - ./.env.prod
    ports:
      - "${PG_PORT_CHAT_SERVER}:5432"
    volumes:
      - pg_vol_chat-server:/var/lib/postgresql/data

  migrator-prod:
    build:
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    depends_on:
      - pg-auth-prod
      - pg-chat-server-prod

  auth-prod:
    container_name: auth
    image: auth
    command: -config-path=.env.prod
    depends_on:
      - pg-auth-prod

  chat-server-prod:
    container_name: chat-server
    image: chat-server
    command: -config-path=.env.prod
    depends_on:
      - pg-chat-server-prod